services:
  backend:
    image: ghcr.io/redtronicbot/poketrade/backend:latest
    networks:
      - proxy
    # Pas de ports ici, Traefik s'en occupe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-redtro.rule=Host(`${API_URL}`)"
      - "traefik.http.routers.api-redtro.tls.certresolver=le"

  frontend:
    image: ghcr.io/redtronicbot/poketrade/frontend:latest
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-redtro.rule=Host(`${FRONT_URL}`)"
      - "traefik.http.routers.front-redtro.tls.certresolver=le"

networks:
  proxy:
    external: true
